### ISSUE TITLE
proxy: section in the main configuration is ignored

### ISSUE THREAD

**Issue by ghomem** [nginxinc/ansible-role-nginx-config#96]
### Describe the bug
Unless I misunderstood the spirit of this:

https://github.com/nginxinc/ansible-role-nginx-config/blob/main/templates/http/default.conf.j2
https://github.com/nginxinc/ansible-role-nginx-config/blob/main/defaults/main/template.yml

I thought a proxy: section inside:

nginx_config_main_template:
  http_settings:

would allow the definition of 

proxy_connect_timeout   90s;
proxy_send_timeout      90s;
proxy_read_timeout      90s;
proxy_buffers           32 4k

### To reproduce
1. Declare a proxy: section inside nginx_config_main_template: http_settings:
2. Apply ansible
3. Note that there are no changes to nginx.conf

### Your environment:
nginxinc.nginx_config, 0.3.3
nginxinc.nginx, 0.19.1
ansible: 2.9.6+dfsg-1
ubuntu 20.04

### Additional context
I apologize if I misunderstood something :-)

**Comment by alessfg** [comment]
I've gone ahead and submitted a PR to address the docs issue on `defaults/main/template.yml`. The actual `proxy` configuration works fine, but you'll have to configure it under `nginx_config_http_template`. Make sure you are pulling the latest commit from `main` too, since release `0.3.3` has different and significantly more limited `proxy` configuration settings.
